// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/23/2024, 1:50:31 AM
const configMerger = require("/Users/richi/Coding/RichieCoding/RichieCoding/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/richi/Coding/RichieCoding/RichieCoding/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/plugins/**/*.{js,ts,mjs}","/Users/richi/Coding/RichieCoding/RichieCoding/composables/**/*.{js,ts,mjs}","/Users/richi/Coding/RichieCoding/RichieCoding/utils/**/*.{js,ts,mjs}","/Users/richi/Coding/RichieCoding/RichieCoding/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/richi/Coding/RichieCoding/RichieCoding/app.config.{js,ts,mjs}"] }));

module.exports = config
